services:
  - type: web
    name: kroi-auto-center
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SANITY_PROJECT_ID
        fromSecret: NEXT_PUBLIC_SANITY_PROJECT_ID
      - key: NEXT_PUBLIC_SANITY_DATASET
        fromSecret: NEXT_PUBLIC_SANITY_DATASET
      - key: SANITY_API_READ_TOKEN
        fromSecret: SANITY_API_READ_TOKEN