services:
  - type: web
    name: kroi-auto-center-clean
    env: node
    region: oregon
    plan: starter
    branch: main

    # Optimized build and start commands
    buildCommand: |
      npm ci --only=production &&
      npm run build &&
      rm -rf .next/cache
    startCommand: npm start

    # Health check endpoint for monitoring
    healthCheckPath: /

    # Performance and security configurations
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SITE_URL
        value: https://kroi-auto-center-clean.onrender.com

      # Shared Sanity CMS Configuration
      - key: NEXT_PUBLIC_SANITY_PROJECT_ID
        value: j2t31xge
      - key: NEXT_PUBLIC_SANITY_DATASET
        value: production
      - key: SANITY_API_TOKEN
        value: skVALaMvvJIxP9krYTpB6SYM6XgH3fe60cDRTpVg05znY5DlDGIx1LvUMre94xah8O1bk6ZIiz5QwNz7aA6B5XisFj8mWid17JAgnWh5tuncOehX5gsYt2oNpVxfpS9xsa1YWxHCjMUxkwGeeH9bynKZGz5OQFwIeNARmmN3ajJCCEfgMUiO

      # Performance optimizations
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"

    # Auto-deployment and scaling
    autoDeploy: true

    # Custom headers for optimization
    headers:
      - path: "/_next/static/*"
        headers:
          - key: "Cache-Control"
            value: "public, max-age=31536000, immutable"
      - path: "/images/*"
        headers:
          - key: "Cache-Control"
            value: "public, max-age=604800"