services:
  - type: web
    name: kroi-auto-center-clean
    env: node
    region: oregon
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SITE_URL
        value: https://kroi-auto-center-clean.onrender.com
      - key: NEXT_PUBLIC_SANITY_PROJECT_ID
        value: j2t31xge
      - key: NEXT_PUBLIC_SANITY_DATASET
        value: production
      - key: SANITY_API_TOKEN
        value: skVALaMvvJIxP9krYTpB6SYM6XgH3fe60cDRTpVg05znY5DlDGIx1LvUMre94xah8O1bk6ZIiz5QwNz7aA6B5XisFj8mWid17JAgnWh5tuncOehX5gsYt2oNpVxfpS9xsa1YWxHCjMUxkwGeeH9bynKZGz5OQFwIeNARmmN3ajJCCEfgMUiO